#!/bin/sh
set -ex
mkdir -p /downloads /logs

# SPA
kapow route add -X GET     '/' -c 'kapow set /response/headers/Content-Type text/html; kapow set /response/body < /video-dl/index.html'
kapow route add -X HEAD    '/' -c 'kapow set /response/status 200'

kapow route add -X POST    '/api/download' -e /video-dl/download-video
kapow route add -X GET     '/api/download' -e /video-dl/list-downloads
kapow route add -X DELETE  '/api/download/{pid:[a-f0-9\-]+}' -e /video-dl/delete-download

kapow route add -X GET     '/api/download/{pid:[a-f0-9\-]+}/status' -e /video-dl/get-download-status
kapow route add -X GET     '/api/download/{pid:[a-f0-9\-]+}/progress' -e /video-dl/get-download-progress
kapow route add -X GET     '/api/download/{pid:[a-f0-9\-]+}/info' -e /video-dl/get-download-info
kapow route add -X GET     '/api/download/{pid:[a-f0-9\-]+}/log/{stream:stdout|stderr}' -e /video-dl/get-download-log -c 'text/plain'

kapow route add -X GET     '/api/config' -e /video-dl/get-config
